//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSCoverageViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSCoverageViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot;
        ///                xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///                xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///                exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///
        ///  &lt;xsl:output method=&quot;html&quot; indent=&quot;yes&quot; /&gt;
        ///  &lt;xsl:param name=&quot;depth&quot; select=&quot;3&quot; /&gt;
        ///  &lt;xsl:param name=&quot;genDate&quot; /&gt;
        ///  &lt;xsl:param name=&quot;linesCovered&quot; /&gt;
        ///  &lt;xsl:param name=&quot;linesPartial&quot; /&gt;
        ///  &lt;xsl:param name=&quot;linesNot&quot; /&gt;
        ///  &lt;xsl:param name=&quot;totalLines&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLTransform {
            get {
                return ResourceManager.GetString("HTMLTransform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;CoverageDSPriv&quot;
        ///           xmlns=&quot;&quot;
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///           xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;
        ///           xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot;&gt;
        ///  &lt;xs:element name=&quot;CoverageDSPriv&quot; msdata:IsDataSet=&quot;true&quot; msdata:UseCurrentLocale=&quot;true&quot; msdata:EnforceConstraints=&quot;False&quot; msprop:Version=&quot;8.00&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
